# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

defaults:

  update-submodules: &update-submodules
    run:
      name: "Update git submodules"
      command: |
        git submodule update --init --recursive

  environment-info: &environment-info
    run:
      name: "Environment info"
      command: |
        echo CXX: $CXX
        echo Generator: $GENERATOR
        cmake --version
        echo CMake options: $CMAKE_OPTIONS
        $CXX --version
        $CXX --version >> toolchain
        echo $GENERATOR >> toolchain

  build-hera: &build-hera
    run:
      name: "Build hera"
      command: |
        cd target-docker
        ./build.sh

jobs:

  linux-gcc-static-debug:
    environment:
      - BUILD_TYPE: Debug
      - CXX: g++
      - CC:  gcc
      - GENERATOR: Unix Makefiles
      - BUILD_PARALLEL_JOBS: 4
      - CMAKE_OPTIONS: -DBUILD_SHARED_LIBS=OFF -DHERA_DEBUGGING=ON -DHERA_BINARYEN=ON -DHERA_WAVM=ON -DHERA_WABT=ON
    docker:
      - image: ethereum/cpp-build-env:clang-9
    steps:
      - checkout
      - *update-submodules
      - *environment-info
      - *build-hera
      # - *restore-deps-cache
      # - *configure
      # - *build
      # - *store-package
      # - *save-deps-cache

# Orchestrate or schedule a set of jobs
workflows:
  ewasm-tests:
    jobs:
      - linux-gcc-static-debug

