# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1

defaults:
  update-submodules: &update-submodules
    run:
      name: "Update git submodules"
      command: |
        git submodule update --init
jobs:
  linux-gcc-static-debug:
    environment:
      - BUILD_TYPE: Debug
      - CXX: g++
      - CC:  gcc
      - GENERATOR: Unix Makefiles
      - BUILD_PARALLEL_JOBS: 4
      - CMAKE_OPTIONS: -DBUILD_SHARED_LIBS=OFF -DHERA_DEBUGGING=ON -DHERA_BINARYEN=ON -DHERA_WAVM=ON -DHERA_WABT=ON
    docker:
      - image: ethereum/cpp-build-env:9
    steps:
      - checkout
      - *update-submodules
      # - *environment-info
      # - *restore-deps-cache
      # - *configure
      # - *build
      # - *store-package
      # - *save-deps-cache

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
      - linux-gcc-static-debug

